language: rust
matrix:
  include:
    - rust: stable
      os: linux
      env: FEATURES=unix
    - rust: stable
      os: osx
      env: FEATURES=unix
    - rust: beta
      os: linux
      env: FEATURES=unix
    - rust: beta
      os: osx
      env: FEATURES=unix
    - rust: nightly
      os: linux
      env: FEATURES="unix nightly"
    - rust: nightly
      os: osx
      env: FEATURES="unix nightly"
cache:
 directories:
  - $HOME/.cargo
sudo: false
script:
  - cargo build --features "$FEATURES"
  - cargo test --features "$FEATURES" --no-fail-fast
